language: rust
cache: cargo
addons:
        apt:
                packages:
                        - kcov
os:
        - linux
        - osx
        - windows
install:
        - cargo install --force cargo-kcov
        - if [ $TRAVIS_OS_NAME = linux ]; kcov --version; fi
script:
        - cargo build
        - cargo test
        - if [ $TRAVIS_OS_NAME = linux ]; then cargo kcov --coveralls; fi

